env:
  browser: true
  es2021: true
extends: standard-with-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  project: './tsconfig.json' # Point to your tsconfig file
rules: {}